#[################################################################
bgfx interface vtbl as generated by c2nim
https://gist.github.com/bkaradzic/05a1c86a6dd57bf86e2d828878e88dc2
investigation required into whether this can be removed
################################################################]#

type
  bgfx_interface_vtbl* {.bycopy.} = object
    attachment_init*: proc (_this: ptr bgfx_attachment_t;
                          _handle: bgfx_texture_handle_t; _access: bgfx_access_t;
                          _layer: uint16; _numLayers: uint16; _mip: uint16;
                          _resolve: uint8_t)
    vertex_layout_begin*: proc (_this: ptr bgfx_vertex_layout_t;
                              _rendererType: bgfx_renderer_type_t): ptr bgfx_vertex_layout_t
    vertex_layout_add*: proc (_this: ptr bgfx_vertex_layout_t;
                            _attrib: bgfx_attrib_t; _num: uint8_t;
                            _type: bgfx_attrib_type_t; _normalized: bool;
                            _asInt: bool): ptr bgfx_vertex_layout_t
    vertex_layout_decode*: proc (_this: ptr bgfx_vertex_layout_t;
                               _attrib: bgfx_attrib_t; _num: ptr uint8_t;
                               _type: ptr bgfx_attrib_type_t;
                               _normalized: ptr bool; _asInt: ptr bool)
    vertex_layout_has*: proc (_this: ptr bgfx_vertex_layout_t; _attrib: bgfx_attrib_t): bool
    vertex_layout_skip*: proc (_this: ptr bgfx_vertex_layout_t; _num: uint8_t): ptr bgfx_vertex_layout_t
    vertex_layout_end*: proc (_this: ptr bgfx_vertex_layout_t)
    vertex_pack*: proc (_input: array[4, cfloat]; _inputNormalized: bool;
                      _attr: bgfx_attrib_t; _layout: ptr bgfx_vertex_layout_t;
                      _data: pointer; _index: uint32)
    vertex_unpack*: proc (_output: array[4, cfloat]; _attr: bgfx_attrib_t;
                        _layout: ptr bgfx_vertex_layout_t; _data: pointer;
                        _index: uint32)
    vertex_convert*: proc (_dstLayout: ptr bgfx_vertex_layout_t; _dstData: pointer;
                         _srcLayout: ptr bgfx_vertex_layout_t; _srcData: pointer;
                         _num: uint32)
    weld_vertices*: proc (_output: pointer; _layout: ptr bgfx_vertex_layout_t;
                        _data: pointer; _num: uint32; _index32: bool;
                        _epsilon: cfloat): uint32
    topology_convert*: proc (_conversion: bgfx_topology_convert_t; _dst: pointer;
                           _dstSize: uint32; _indices: pointer;
                           _numIndices: uint32; _index32: bool): uint32
    topology_sort_tri_list*: proc (_sort: bgfx_topology_sort_t; _dst: pointer;
                                 _dstSize: uint32; _dir: array[3, cfloat];
                                 _pos: array[3, cfloat]; _vertices: pointer;
                                 _stride: uint32; _indices: pointer;
                                 _numIndices: uint32; _index32: bool)
    get_supported_renderers*: proc (_max: uint8_t; _enum: ptr bgfx_renderer_type_t): uint8_t
    get_renderer_name*: proc (_type: bgfx_renderer_type_t): cstring
    init_ctor*: proc (_init: ptr bgfx_init_t)
    init*: proc (_init: ptr bgfx_init_t): bool
    shutdown*: proc ()
    reset*: proc (_width: uint32; _height: uint32; _flags: uint32;
                _format: bgfx_texture_format_t)
    frame*: proc (_capture: bool): uint32
    get_renderer_type*: proc (): bgfx_renderer_type_t
    get_caps*: proc (): ptr bgfx_caps_t
    get_stats*: proc (): ptr bgfx_stats_t
    alloc*: proc (_size: uint32): ptr bgfx_memory_t
    copy*: proc (_data: pointer; _size: uint32): ptr bgfx_memory_t
    make_ref*: proc (_data: pointer; _size: uint32): ptr bgfx_memory_t
    make_ref_release*: proc (_data: pointer; _size: uint32;
                           _releaseFn: bgfx_release_fn_t; _userData: pointer): ptr bgfx_memory_t
    set_debug*: proc (_debug: uint32)
    dbg_text_clear*: proc (_attr: uint8_t; _small: bool)
    dbg_text_printf*: proc (_x: uint16; _y: uint16; _attr: uint8_t; _format: cstring) {.
        varargs.}
    dbg_text_vprintf*: proc (_x: uint16; _y: uint16; _attr: uint8_t;
                           _format: cstring; _argList: va_list)
    dbg_text_image*: proc (_x: uint16; _y: uint16; _width: uint16;
                         _height: uint16; _data: pointer; _pitch: uint16)
    create_index_buffer*: proc (_mem: ptr bgfx_memory_t; _flags: uint16): bgfx_index_buffer_handle_t
    set_index_buffer_name*: proc (_handle: bgfx_index_buffer_handle_t;
                                _name: cstring; _len: int32_t)
    destroy_index_buffer*: proc (_handle: bgfx_index_buffer_handle_t)
    create_vertex_layout*: proc (_layout: ptr bgfx_vertex_layout_t): bgfx_vertex_layout_handle_t
    destroy_vertex_layout*: proc (_layoutHandle: bgfx_vertex_layout_handle_t)
    create_vertex_buffer*: proc (_mem: ptr bgfx_memory_t;
                               _layout: ptr bgfx_vertex_layout_t; _flags: uint16): bgfx_vertex_buffer_handle_t
    set_vertex_buffer_name*: proc (_handle: bgfx_vertex_buffer_handle_t;
                                 _name: cstring; _len: int32_t)
    destroy_vertex_buffer*: proc (_handle: bgfx_vertex_buffer_handle_t)
    create_dynamic_index_buffer*: proc (_num: uint32; _flags: uint16): bgfx_dynamic_index_buffer_handle_t
    create_dynamic_index_buffer_mem*: proc (_mem: ptr bgfx_memory_t; _flags: uint16): bgfx_dynamic_index_buffer_handle_t
    update_dynamic_index_buffer*: proc (_handle: bgfx_dynamic_index_buffer_handle_t;
                                      _startIndex: uint32;
                                      _mem: ptr bgfx_memory_t)
    destroy_dynamic_index_buffer*: proc (_handle: bgfx_dynamic_index_buffer_handle_t)
    create_dynamic_vertex_buffer*: proc (_num: uint32;
                                       _layout: ptr bgfx_vertex_layout_t;
                                       _flags: uint16): bgfx_dynamic_vertex_buffer_handle_t
    create_dynamic_vertex_buffer_mem*: proc (_mem: ptr bgfx_memory_t;
        _layout: ptr bgfx_vertex_layout_t; _flags: uint16): bgfx_dynamic_vertex_buffer_handle_t
    update_dynamic_vertex_buffer*: proc (_handle: bgfx_dynamic_vertex_buffer_handle_t;
                                       _startVertex: uint32;
                                       _mem: ptr bgfx_memory_t)
    destroy_dynamic_vertex_buffer*: proc (_handle: bgfx_dynamic_vertex_buffer_handle_t)
    get_avail_transient_index_buffer*: proc (_num: uint32; _index32: bool): uint32
    get_avail_transient_vertex_buffer*: proc (_num: uint32;
        _layout: ptr bgfx_vertex_layout_t): uint32
    get_avail_instance_data_buffer*: proc (_num: uint32; _stride: uint16): uint32
    alloc_transient_index_buffer*: proc (_tib: ptr bgfx_transient_index_buffer_t;
                                       _num: uint32; _index32: bool)
    alloc_transient_vertex_buffer*: proc (_tvb: ptr bgfx_transient_vertex_buffer_t;
                                        _num: uint32;
                                        _layout: ptr bgfx_vertex_layout_t)
    alloc_transient_buffers*: proc (_tvb: ptr bgfx_transient_vertex_buffer_t;
                                  _layout: ptr bgfx_vertex_layout_t;
                                  _numVertices: uint32;
                                  _tib: ptr bgfx_transient_index_buffer_t;
                                  _numIndices: uint32; _index32: bool): bool
    alloc_instance_data_buffer*: proc (_idb: ptr bgfx_instance_data_buffer_t;
                                     _num: uint32; _stride: uint16)
    create_indirect_buffer*: proc (_num: uint32): bgfx_indirect_buffer_handle_t
    destroy_indirect_buffer*: proc (_handle: bgfx_indirect_buffer_handle_t)
    create_shader*: proc (_mem: ptr bgfx_memory_t): bgfx_shader_handle_t
    get_shader_uniforms*: proc (_handle: bgfx_shader_handle_t;
                              _uniforms: ptr bgfx_uniform_handle_t; _max: uint16): uint16
    set_shader_name*: proc (_handle: bgfx_shader_handle_t; _name: cstring;
                          _len: int32_t)
    destroy_shader*: proc (_handle: bgfx_shader_handle_t)
    create_program*: proc (_vsh: bgfx_shader_handle_t; _fsh: bgfx_shader_handle_t;
                         _destroyShaders: bool): bgfx_program_handle_t
    create_compute_program*: proc (_csh: bgfx_shader_handle_t; _destroyShaders: bool): bgfx_program_handle_t
    destroy_program*: proc (_handle: bgfx_program_handle_t)
    is_texture_valid*: proc (_depth: uint16; _cubeMap: bool; _numLayers: uint16;
                           _format: bgfx_texture_format_t; _flags: uint64_t): bool
    is_frame_buffer_valid*: proc (_num: uint8_t; _attachment: ptr bgfx_attachment_t): bool
    calc_texture_size*: proc (_info: ptr bgfx_texture_info_t; _width: uint16;
                            _height: uint16; _depth: uint16; _cubeMap: bool;
                            _hasMips: bool; _numLayers: uint16;
                            _format: bgfx_texture_format_t)
    create_texture*: proc (_mem: ptr bgfx_memory_t; _flags: uint64_t; _skip: uint8_t;
                         _info: ptr bgfx_texture_info_t): bgfx_texture_handle_t
    create_texture_2d*: proc (_width: uint16; _height: uint16; _hasMips: bool;
                            _numLayers: uint16; _format: bgfx_texture_format_t;
                            _flags: uint64_t; _mem: ptr bgfx_memory_t): bgfx_texture_handle_t
    create_texture_2d_scaled*: proc (_ratio: bgfx_backbuffer_ratio_t;
                                   _hasMips: bool; _numLayers: uint16;
                                   _format: bgfx_texture_format_t;
                                   _flags: uint64_t): bgfx_texture_handle_t
    create_texture_3d*: proc (_width: uint16; _height: uint16; _depth: uint16;
                            _hasMips: bool; _format: bgfx_texture_format_t;
                            _flags: uint64_t; _mem: ptr bgfx_memory_t): bgfx_texture_handle_t
    create_texture_cube*: proc (_size: uint16; _hasMips: bool; _numLayers: uint16;
                              _format: bgfx_texture_format_t; _flags: uint64_t;
                              _mem: ptr bgfx_memory_t): bgfx_texture_handle_t
    update_texture_2d*: proc (_handle: bgfx_texture_handle_t; _layer: uint16;
                            _mip: uint8_t; _x: uint16; _y: uint16;
                            _width: uint16; _height: uint16;
                            _mem: ptr bgfx_memory_t; _pitch: uint16)
    update_texture_3d*: proc (_handle: bgfx_texture_handle_t; _mip: uint8_t;
                            _x: uint16; _y: uint16; _z: uint16;
                            _width: uint16; _height: uint16; _depth: uint16;
                            _mem: ptr bgfx_memory_t)
    update_texture_cube*: proc (_handle: bgfx_texture_handle_t; _layer: uint16;
                              _side: uint8_t; _mip: uint8_t; _x: uint16;
                              _y: uint16; _width: uint16; _height: uint16;
                              _mem: ptr bgfx_memory_t; _pitch: uint16)
    read_texture*: proc (_handle: bgfx_texture_handle_t; _data: pointer; _mip: uint8_t): uint32
    set_texture_name*: proc (_handle: bgfx_texture_handle_t; _name: cstring;
                           _len: int32_t)
    get_direct_access_ptr*: proc (_handle: bgfx_texture_handle_t): pointer
    destroy_texture*: proc (_handle: bgfx_texture_handle_t)
    create_frame_buffer*: proc (_width: uint16; _height: uint16;
                              _format: bgfx_texture_format_t;
                              _textureFlags: uint64_t): bgfx_frame_buffer_handle_t
    create_frame_buffer_scaled*: proc (_ratio: bgfx_backbuffer_ratio_t;
                                     _format: bgfx_texture_format_t;
                                     _textureFlags: uint64_t): bgfx_frame_buffer_handle_t
    create_frame_buffer_from_handles*: proc (_num: uint8_t;
        _handles: ptr bgfx_texture_handle_t; _destroyTexture: bool): bgfx_frame_buffer_handle_t
    create_frame_buffer_from_attachment*: proc (_num: uint8_t;
        _attachment: ptr bgfx_attachment_t; _destroyTexture: bool): bgfx_frame_buffer_handle_t
    create_frame_buffer_from_nwh*: proc (_nwh: pointer; _width: uint16;
                                       _height: uint16;
                                       _format: bgfx_texture_format_t;
                                       _depthFormat: bgfx_texture_format_t): bgfx_frame_buffer_handle_t
    set_frame_buffer_name*: proc (_handle: bgfx_frame_buffer_handle_t;
                                _name: cstring; _len: int32_t)
    get_texture*: proc (_handle: bgfx_frame_buffer_handle_t; _attachment: uint8_t): bgfx_texture_handle_t
    destroy_frame_buffer*: proc (_handle: bgfx_frame_buffer_handle_t)
    create_uniform*: proc (_name: cstring; _type: bgfx_uniform_type_t; _num: uint16): bgfx_uniform_handle_t
    get_uniform_info*: proc (_handle: bgfx_uniform_handle_t;
                           _info: ptr bgfx_uniform_info_t)
    destroy_uniform*: proc (_handle: bgfx_uniform_handle_t)
    create_occlusion_query*: proc (): bgfx_occlusion_query_handle_t
    get_result*: proc (_handle: bgfx_occlusion_query_handle_t; _result: ptr int32_t): bgfx_occlusion_query_result_t
    destroy_occlusion_query*: proc (_handle: bgfx_occlusion_query_handle_t)
    set_palette_color*: proc (_index: uint8_t; _rgba: array[4, cfloat])
    set_palette_color_rgba8*: proc (_index: uint8_t; _rgba: uint32)
    set_view_name*: proc (_id: bgfx_view_id_t; _name: cstring)
    set_view_rect*: proc (_id: bgfx_view_id_t; _x: uint16; _y: uint16;
                        _width: uint16; _height: uint16)
    set_view_rect_ratio*: proc (_id: bgfx_view_id_t; _x: uint16; _y: uint16;
                              _ratio: bgfx_backbuffer_ratio_t)
    set_view_scissor*: proc (_id: bgfx_view_id_t; _x: uint16; _y: uint16;
                           _width: uint16; _height: uint16)
    set_view_clear*: proc (_id: bgfx_view_id_t; _flags: uint16; _rgba: uint32;
                         _depth: cfloat; _stencil: uint8_t)
    set_view_clear_mrt*: proc (_id: bgfx_view_id_t; _flags: uint16; _depth: cfloat;
                             _stencil: uint8_t; _c0: uint8_t; _c1: uint8_t;
                             _c2: uint8_t; _c3: uint8_t; _c4: uint8_t; _c5: uint8_t;
                             _c6: uint8_t; _c7: uint8_t)
    set_view_mode*: proc (_id: bgfx_view_id_t; _mode: bgfx_view_mode_t)
    set_view_frame_buffer*: proc (_id: bgfx_view_id_t;
                                _handle: bgfx_frame_buffer_handle_t)
    set_view_transform*: proc (_id: bgfx_view_id_t; _view: pointer; _proj: pointer)
    set_view_order*: proc (_id: bgfx_view_id_t; _num: uint16;
                         _order: ptr bgfx_view_id_t)
    reset_view*: proc (_id: bgfx_view_id_t)
    encoder_begin*: proc (_forThread: bool): ptr bgfx_encoder_t
    encoder_end*: proc (_encoder: ptr bgfx_encoder_t)
    encoder_set_marker*: proc (_this: ptr bgfx_encoder_t; _marker: cstring)
    encoder_set_state*: proc (_this: ptr bgfx_encoder_t; _state: uint64_t;
                            _rgba: uint32)
    encoder_set_condition*: proc (_this: ptr bgfx_encoder_t;
                                _handle: bgfx_occlusion_query_handle_t;
                                _visible: bool)
    encoder_set_stencil*: proc (_this: ptr bgfx_encoder_t; _fstencil: uint32;
                              _bstencil: uint32)
    encoder_set_scissor*: proc (_this: ptr bgfx_encoder_t; _x: uint16; _y: uint16;
                              _width: uint16; _height: uint16): uint16
    encoder_set_scissor_cached*: proc (_this: ptr bgfx_encoder_t; _cache: uint16)
    encoder_set_transform*: proc (_this: ptr bgfx_encoder_t; _mtx: pointer;
                                _num: uint16): uint32
    encoder_set_transform_cached*: proc (_this: ptr bgfx_encoder_t; _cache: uint32;
                                       _num: uint16)
    encoder_alloc_transform*: proc (_this: ptr bgfx_encoder_t;
                                  _transform: ptr bgfx_transform_t; _num: uint16): uint32
    encoder_set_uniform*: proc (_this: ptr bgfx_encoder_t;
                              _handle: bgfx_uniform_handle_t; _value: pointer;
                              _num: uint16)
    encoder_set_index_buffer*: proc (_this: ptr bgfx_encoder_t;
                                   _handle: bgfx_index_buffer_handle_t;
                                   _firstIndex: uint32; _numIndices: uint32)
    encoder_set_dynamic_index_buffer*: proc (_this: ptr bgfx_encoder_t;
        _handle: bgfx_dynamic_index_buffer_handle_t; _firstIndex: uint32;
        _numIndices: uint32)
    encoder_set_transient_index_buffer*: proc (_this: ptr bgfx_encoder_t;
        _tib: ptr bgfx_transient_index_buffer_t; _firstIndex: uint32;
        _numIndices: uint32)
    encoder_set_vertex_buffer*: proc (_this: ptr bgfx_encoder_t; _stream: uint8_t;
                                    _handle: bgfx_vertex_buffer_handle_t;
                                    _startVertex: uint32; _numVertices: uint32)
    encoder_set_vertex_buffer_with_layout*: proc (_this: ptr bgfx_encoder_t;
        _stream: uint8_t; _handle: bgfx_vertex_buffer_handle_t;
        _startVertex: uint32; _numVertices: uint32;
        _layoutHandle: bgfx_vertex_layout_handle_t)
    encoder_set_dynamic_vertex_buffer*: proc (_this: ptr bgfx_encoder_t;
        _stream: uint8_t; _handle: bgfx_dynamic_vertex_buffer_handle_t;
        _startVertex: uint32; _numVertices: uint32)
    encoder_set_dynamic_vertex_buffer_with_layout*: proc (
        _this: ptr bgfx_encoder_t; _stream: uint8_t;
        _handle: bgfx_dynamic_vertex_buffer_handle_t; _startVertex: uint32;
        _numVertices: uint32; _layoutHandle: bgfx_vertex_layout_handle_t)
    encoder_set_transient_vertex_buffer*: proc (_this: ptr bgfx_encoder_t;
        _stream: uint8_t; _tvb: ptr bgfx_transient_vertex_buffer_t;
        _startVertex: uint32; _numVertices: uint32)
    encoder_set_transient_vertex_buffer_with_layout*: proc (
        _this: ptr bgfx_encoder_t; _stream: uint8_t;
        _tvb: ptr bgfx_transient_vertex_buffer_t; _startVertex: uint32;
        _numVertices: uint32; _layoutHandle: bgfx_vertex_layout_handle_t)
    encoder_set_vertex_count*: proc (_this: ptr bgfx_encoder_t;
                                   _numVertices: uint32)
    encoder_set_instance_data_buffer*: proc (_this: ptr bgfx_encoder_t;
        _idb: ptr bgfx_instance_data_buffer_t; _start: uint32; _num: uint32)
    encoder_set_instance_data_from_vertex_buffer*: proc (
        _this: ptr bgfx_encoder_t; _handle: bgfx_vertex_buffer_handle_t;
        _startVertex: uint32; _num: uint32)
    encoder_set_instance_data_from_dynamic_vertex_buffer*: proc (
        _this: ptr bgfx_encoder_t; _handle: bgfx_dynamic_vertex_buffer_handle_t;
        _startVertex: uint32; _num: uint32)
    encoder_set_instance_count*: proc (_this: ptr bgfx_encoder_t;
                                     _numInstances: uint32)
    encoder_set_texture*: proc (_this: ptr bgfx_encoder_t; _stage: uint8_t;
                              _sampler: bgfx_uniform_handle_t;
                              _handle: bgfx_texture_handle_t; _flags: uint32)
    encoder_touch*: proc (_this: ptr bgfx_encoder_t; _id: bgfx_view_id_t)
    encoder_submit*: proc (_this: ptr bgfx_encoder_t; _id: bgfx_view_id_t;
                         _program: bgfx_program_handle_t; _depth: uint32;
                         _flags: uint8_t)
    encoder_submit_occlusion_query*: proc (_this: ptr bgfx_encoder_t;
        _id: bgfx_view_id_t; _program: bgfx_program_handle_t;
        _occlusionQuery: bgfx_occlusion_query_handle_t; _depth: uint32;
        _flags: uint8_t)
    encoder_submit_indirect*: proc (_this: ptr bgfx_encoder_t; _id: bgfx_view_id_t;
                                  _program: bgfx_program_handle_t; _indirectHandle: bgfx_indirect_buffer_handle_t;
                                  _start: uint16; _num: uint16;
                                  _depth: uint32; _flags: uint8_t)
    encoder_set_compute_index_buffer*: proc (_this: ptr bgfx_encoder_t;
        _stage: uint8_t; _handle: bgfx_index_buffer_handle_t; _access: bgfx_access_t)
    encoder_set_compute_vertex_buffer*: proc (_this: ptr bgfx_encoder_t;
        _stage: uint8_t; _handle: bgfx_vertex_buffer_handle_t;
        _access: bgfx_access_t)
    encoder_set_compute_dynamic_index_buffer*: proc (_this: ptr bgfx_encoder_t;
        _stage: uint8_t; _handle: bgfx_dynamic_index_buffer_handle_t;
        _access: bgfx_access_t)
    encoder_set_compute_dynamic_vertex_buffer*: proc (_this: ptr bgfx_encoder_t;
        _stage: uint8_t; _handle: bgfx_dynamic_vertex_buffer_handle_t;
        _access: bgfx_access_t)
    encoder_set_compute_indirect_buffer*: proc (_this: ptr bgfx_encoder_t;
        _stage: uint8_t; _handle: bgfx_indirect_buffer_handle_t;
        _access: bgfx_access_t)
    encoder_set_image*: proc (_this: ptr bgfx_encoder_t; _stage: uint8_t;
                            _handle: bgfx_texture_handle_t; _mip: uint8_t;
                            _access: bgfx_access_t; _format: bgfx_texture_format_t)
    encoder_dispatch*: proc (_this: ptr bgfx_encoder_t; _id: bgfx_view_id_t;
                           _program: bgfx_program_handle_t; _numX: uint32;
                           _numY: uint32; _numZ: uint32; _flags: uint8_t)
    encoder_dispatch_indirect*: proc (_this: ptr bgfx_encoder_t; _id: bgfx_view_id_t;
                                    _program: bgfx_program_handle_t;
        _indirectHandle: bgfx_indirect_buffer_handle_t; _start: uint16;
                                    _num: uint16; _flags: uint8_t)
    encoder_discard*: proc (_this: ptr bgfx_encoder_t; _flags: uint8_t)
    encoder_blit*: proc (_this: ptr bgfx_encoder_t; _id: bgfx_view_id_t;
                       _dst: bgfx_texture_handle_t; _dstMip: uint8_t;
                       _dstX: uint16; _dstY: uint16; _dstZ: uint16;
                       _src: bgfx_texture_handle_t; _srcMip: uint8_t;
                       _srcX: uint16; _srcY: uint16; _srcZ: uint16;
                       _width: uint16; _height: uint16; _depth: uint16)
    request_screen_shot*: proc (_handle: bgfx_frame_buffer_handle_t;
                              _filePath: cstring)
    render_frame*: proc (_msecs: int32_t): bgfx_render_frame_t
    set_platform_data*: proc (_data: ptr bgfx_platform_data_t)
    get_internal_data*: proc (): ptr bgfx_internal_data_t
    override_internal_texture_ptr*: proc (_handle: bgfx_texture_handle_t;
                                        _ptr: uintptr_t): uintptr_t
    override_internal_texture*: proc (_handle: bgfx_texture_handle_t;
                                    _width: uint16; _height: uint16;
                                    _numMips: uint8_t;
                                    _format: bgfx_texture_format_t;
                                    _flags: uint64_t): uintptr_t
    set_marker*: proc (_marker: cstring)
    set_state*: proc (_state: uint64_t; _rgba: uint32)
    set_condition*: proc (_handle: bgfx_occlusion_query_handle_t; _visible: bool)
    set_stencil*: proc (_fstencil: uint32; _bstencil: uint32)
    set_scissor*: proc (_x: uint16; _y: uint16; _width: uint16; _height: uint16): uint16
    set_scissor_cached*: proc (_cache: uint16)
    set_transform*: proc (_mtx: pointer; _num: uint16): uint32
    set_transform_cached*: proc (_cache: uint32; _num: uint16)
    alloc_transform*: proc (_transform: ptr bgfx_transform_t; _num: uint16): uint32
    set_uniform*: proc (_handle: bgfx_uniform_handle_t; _value: pointer;
                      _num: uint16)
    set_index_buffer*: proc (_handle: bgfx_index_buffer_handle_t;
                           _firstIndex: uint32; _numIndices: uint32)
    set_dynamic_index_buffer*: proc (_handle: bgfx_dynamic_index_buffer_handle_t;
                                   _firstIndex: uint32; _numIndices: uint32)
    set_transient_index_buffer*: proc (_tib: ptr bgfx_transient_index_buffer_t;
                                     _firstIndex: uint32; _numIndices: uint32)
    set_vertex_buffer*: proc (_stream: uint8_t;
                            _handle: bgfx_vertex_buffer_handle_t;
                            _startVertex: uint32; _numVertices: uint32)
    set_vertex_buffer_with_layout*: proc (_stream: uint8_t;
                                        _handle: bgfx_vertex_buffer_handle_t;
                                        _startVertex: uint32;
                                        _numVertices: uint32; _layoutHandle: bgfx_vertex_layout_handle_t)
    set_dynamic_vertex_buffer*: proc (_stream: uint8_t; _handle: bgfx_dynamic_vertex_buffer_handle_t;
                                    _startVertex: uint32; _numVertices: uint32)
    set_dynamic_vertex_buffer_with_layout*: proc (_stream: uint8_t;
        _handle: bgfx_dynamic_vertex_buffer_handle_t; _startVertex: uint32;
        _numVertices: uint32; _layoutHandle: bgfx_vertex_layout_handle_t)
    set_transient_vertex_buffer*: proc (_stream: uint8_t;
                                      _tvb: ptr bgfx_transient_vertex_buffer_t;
                                      _startVertex: uint32;
                                      _numVertices: uint32)
    set_transient_vertex_buffer_with_layout*: proc (_stream: uint8_t;
        _tvb: ptr bgfx_transient_vertex_buffer_t; _startVertex: uint32;
        _numVertices: uint32; _layoutHandle: bgfx_vertex_layout_handle_t)
    set_vertex_count*: proc (_numVertices: uint32)
    set_instance_data_buffer*: proc (_idb: ptr bgfx_instance_data_buffer_t;
                                   _start: uint32; _num: uint32)
    set_instance_data_from_vertex_buffer*: proc (
        _handle: bgfx_vertex_buffer_handle_t; _startVertex: uint32; _num: uint32)
    set_instance_data_from_dynamic_vertex_buffer*: proc (
        _handle: bgfx_dynamic_vertex_buffer_handle_t; _startVertex: uint32;
        _num: uint32)
    set_instance_count*: proc (_numInstances: uint32)
    set_texture*: proc (_stage: uint8_t; _sampler: bgfx_uniform_handle_t;
                      _handle: bgfx_texture_handle_t; _flags: uint32)
    touch*: proc (_id: bgfx_view_id_t)
    submit*: proc (_id: bgfx_view_id_t; _program: bgfx_program_handle_t;
                 _depth: uint32; _flags: uint8_t)
    submit_occlusion_query*: proc (_id: bgfx_view_id_t;
                                 _program: bgfx_program_handle_t; _occlusionQuery: bgfx_occlusion_query_handle_t;
                                 _depth: uint32; _flags: uint8_t)
    submit_indirect*: proc (_id: bgfx_view_id_t; _program: bgfx_program_handle_t;
                          _indirectHandle: bgfx_indirect_buffer_handle_t;
                          _start: uint16; _num: uint16; _depth: uint32;
                          _flags: uint8_t)
    set_compute_index_buffer*: proc (_stage: uint8_t;
                                   _handle: bgfx_index_buffer_handle_t;
                                   _access: bgfx_access_t)
    set_compute_vertex_buffer*: proc (_stage: uint8_t;
                                    _handle: bgfx_vertex_buffer_handle_t;
                                    _access: bgfx_access_t)
    set_compute_dynamic_index_buffer*: proc (_stage: uint8_t;
        _handle: bgfx_dynamic_index_buffer_handle_t; _access: bgfx_access_t)
    set_compute_dynamic_vertex_buffer*: proc (_stage: uint8_t;
        _handle: bgfx_dynamic_vertex_buffer_handle_t; _access: bgfx_access_t)
    set_compute_indirect_buffer*: proc (_stage: uint8_t;
                                      _handle: bgfx_indirect_buffer_handle_t;
                                      _access: bgfx_access_t)
    set_image*: proc (_stage: uint8_t; _handle: bgfx_texture_handle_t; _mip: uint8_t;
                    _access: bgfx_access_t; _format: bgfx_texture_format_t)
    dispatch*: proc (_id: bgfx_view_id_t; _program: bgfx_program_handle_t;
                   _numX: uint32; _numY: uint32; _numZ: uint32; _flags: uint8_t)
    dispatch_indirect*: proc (_id: bgfx_view_id_t; _program: bgfx_program_handle_t;
                            _indirectHandle: bgfx_indirect_buffer_handle_t;
                            _start: uint16; _num: uint16; _flags: uint8_t)
    `discard`*: proc (_flags: uint8_t)
    blit*: proc (_id: bgfx_view_id_t; _dst: bgfx_texture_handle_t; _dstMip: uint8_t;
               _dstX: uint16; _dstY: uint16; _dstZ: uint16;
               _src: bgfx_texture_handle_t; _srcMip: uint8_t; _srcX: uint16;
               _srcY: uint16; _srcZ: uint16; _width: uint16; _height: uint16;
               _depth: uint16)



type
  PFN_BGFX_GET_INTERFACE* = proc (_version: uint32): ptr bgfx_interface_vtbl_t


proc bgfx_get_interface*(_version: uint32): ptr bgfx_interface_vtbl_t